//
// =================================================================
//
// BeatDrop/MDropDX12 - A Milkdrop2 Music Visualizer
//
// Authors : Maxim Volskiy (https://github.com/mvsoft74/BeatDrop) et al.
//
// From the readme :
// BeatDrop is a stand - alone implementation of the amazing Milkdrop2 Winamp plug-in.
// It lets you experience the stunning visual 2D effects with your music player of choice.
// No additional configuration steps needed!Just start BeatDrop and play your music.
// Use BeatDrop with your favourite Music player.
//
// The concept is realized by using audio loopback capture by Matthew van Eerde
// https://github.com/mvaneerde/blog
//
// =================================================================
//
//	                  Modified for Spout output
//
//                https://github.com/leadedge/BeatDrop
//
//					      Lynn Jarvis 2018-2023
//
//                       http://spout.zeal.co/
//
// Spout output can be imported into any host program with Spout support
// or by using the SpoutReceiver FreeframeGL plugin for Freeframe hosts.
// The visuals will then react to audio generated by the host itself.
// Search for "SPOUT" to find code changes.
//
//	Key functions changed slightly :
//
//  ESC  exit help / menus
//
//  F1   help
//  F4   preset name
//  F5   frames per second
//  F6   preset rating
//  F8   change preset folder
//	F9   toggle max fps 60/30
//  F12  show / hide render window
//
//  PRESET BROWSING :
//  SPACE     soft transition to next preset
//  H         instant hard cut to next preset
//  BACKSPACE go back to previous preset
//  ` or ~lock / unlock current preset
//  R         toggle random / sequential preset order
//  L         load specific preset
//  + / -rate current preset(better / worse)
//
//  PRESET EDITING AND SAVING
//  M    show / hide preset - editing Menu
//  S    save new preset
//  A    do random mini - mash - up
//  D    toggle warp & comp shader locks
//
// Revisons : see plugin.cpp
// NOTE : The device must be D3D9ex and not D3D9.
// See : void InitD3d(HWND hwnd, int width, int height)
// Changes throughout. Search for "DX9EX".
// Credit : Patrick Pomerleau - NEST Immersion.
//
// =================================================================
//
// Licencing :
//
// BeatDrop Copyright (c) 2018 Maxim Volskiy and individual contributors
// licenced with the 3-Clause BSD License (https://opensource.org/licenses/BSD-3-Clause) 
// with the exception of where otherwise noted.
//
// Original MilkDrop code by Ryan Geiss and Rovastar (John Baker)
// https://sourceforge.net/projects/milkdrop2/
//
// =================================================================
//
// Spout modifications : Copyright(C) 2018-2023, Lynn Jarvis. All rights reserved.
//
// licenced with 3-Clause BSD License.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met :
// 
// 1. Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
// 
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"	AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE	ARE DISCLAIMED.
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES(INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// 
// =================================================================

#ifdef DEBUG
#define _CRTDBG_MAP_ALLOC
#endif

// Define VK_B if it is not already defined
#ifndef VK_B
#define VK_B 0x42 // ASCII code for 'B'
#endif

// Define VK_C if it is not already defined
#ifndef VK_C
#define VK_C 0x43 // ASCII code for 'C'
#endif

#ifndef VK_D
#define VK_D 0x44 // ASCII code for 'D'
#endif

#ifndef VK_M
#define VK_M 0x4D // ASCII code for 'M'
#endif

#ifndef VK_A
#define VK_A 0x41 // ASCII code for 'A'
#endif

#include <stdlib.h>
#include <malloc.h>
#include <crtdbg.h>

#include <windows.h>
#include <process.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <wrl/client.h>
#include <math.h>
#include <dwmapi.h>

using Microsoft::WRL::ComPtr;

#include <ShellScalingApi.h> // for dpi awareness
#pragma comment(lib, "shcore.lib") // for dpi awareness
// older Windows versions: Entry Point Not Found Fix

#include "engine.h"
#include "engine_helpers.h"
#include "resource.h"
#include "engineshell.h"
#include "utility.h"

#include <mutex>
#include <atomic>

//#include <core/sdk/constants.h>
//#include <core/sdk/IPcmVisualizer.h>
//#include <core/sdk/IPlaybackRemote.h>

#include "..\audio\common.h"
#include "mdropdx12.h"
#include <locale>
#include <codecvt>
#include "Milkdrop2PcmVisualizer.h"

namespace fs = std::filesystem;

#define DLL_EXPORT __declspec(dllexport)
//#define COMPILE_AS_DLL
#define SAMPLE_SIZE 576
#define DEFAULT_WIDTH 720;
#define DEFAULT_HEIGHT 720;

namespace mdrop { Engine g_engine; }
using namespace mdrop;
MDropDX12 mdropdx12;
HINSTANCE api_orig_hinstance = nullptr;
_locale_t g_use_C_locale;
char keyMappings[8];

// SPOUT
// ===============================================
static int nBeatDrops = 0; // Number of BeatDrop instances already running
BOOL CALLBACK GetWindowNames(HWND h, LPARAM l); // Window enumerator callback
// ===============================================

// DX12 device objects (created in InitD3d, released in DeinitD3d)
static ComPtr<ID3D12Device>       pD3DDevice;
static ComPtr<ID3D12CommandQueue> pCommandQueue;
static ComPtr<IDXGIFactory4>      pDXGIFactory;

static LONG lastWindowStyle = 0;
static LONG lastWindowStyleEx = 0;

static bool fullscreen = false;
static bool stretch = false;
static bool borderless = false;
static bool clickthrough = false;
static RECT lastRect = { 0 };

static HMODULE module = nullptr;
static std::atomic<HANDLE> threadRender = nullptr;
static std::atomic<HANDLE> threadSetup = nullptr;
static unsigned threadId = 0;
static std::mutex pcmMutex;
static unsigned char pcmLeftIn[SAMPLE_SIZE];
static unsigned char pcmRightIn[SAMPLE_SIZE];
static unsigned char pcmLeftOut[SAMPLE_SIZE];
static unsigned char pcmRightOut[SAMPLE_SIZE];

wchar_t m_szAudioDevice[MAX_PATH];
wchar_t m_szAudioDevicePrevious[MAX_PATH];

HANDLE hThreadLoopbackCapture;

bool pauseRender = false;

static HICON icon = nullptr;

// --- IPC window thread (non-blocking Milkwave Remote handler) ---
static std::atomic<HANDLE> threadIPC = nullptr;
static unsigned threadIPCId = 0;
std::atomic<HWND> g_hRenderWindow{nullptr};  // set after render window CreateWindowW
std::atomic<bool> g_bIPCRunning{false};
WCHAR g_szIPCWindowTitle[256] = {};  // title for IPC window (set before thread start)


// SPOUT
// ===============================================
BOOL CALLBACK GetWindowNames(HWND h, LPARAM l) {
  if (h == NULL)
    return FALSE;

  char search_window_name[MAX_PATH];

  if (IsWindow(h) && IsWindowVisible(h)) {
    GetWindowTextA(h, search_window_name, MAX_PATH);
    if (search_window_name[0]) {
      // Does the search window name contain "MDropDX12 Visualizer" ?
      if (strstr(search_window_name, "MDropDX12 Visualizer") != NULL) {
        nBeatDrops++;
      }
    }
  }
  return TRUE;
}
// ===============================================

// --- IPC hidden window: receives WM_COPYDATA on its own thread, forwards to render thread ---
static LRESULT CALLBACK IPCWindowProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) {
  switch (uMsg) {
  case WM_COPYDATA:
  {
    PCOPYDATASTRUCT pCopyData = (PCOPYDATASTRUCT)lParam;
    if (pCopyData->dwData == 1) {
      size_t cbData = pCopyData->cbData;
      size_t messageLength = cbData / sizeof(wchar_t);
      if (messageLength == 0)
        return TRUE;

      // Copy message to heap (WM_COPYDATA buffer is only valid during SendMessage)
      wchar_t* copy = (wchar_t*)malloc((messageLength + 1) * sizeof(wchar_t));
      if (!copy)
        return TRUE;
      memcpy(copy, pCopyData->lpData, cbData);
      copy[messageLength] = L'\0';  // ensure null-terminated

      // Post to render window — render thread will call LaunchMessage and free the buffer
      HWND hRender = g_hRenderWindow.load();
      if (hRender && IsWindow(hRender)) {
        if (!PostMessage(hRender, WM_MW_IPC_MESSAGE, 0, (LPARAM)copy)) {
          free(copy);  // PostMessage failed (window closing?)
        }
      }
      else {
        free(copy);  // render window not ready yet
      }
      return TRUE;  // message handled — unblocks sender immediately
    }
    break;
  }
  case WM_DESTROY:
    PostQuitMessage(0);
    return 0;
  }
  return DefWindowProc(hWnd, uMsg, wParam, lParam);
}

static unsigned __stdcall IPCWindowThread(void* data) {
  HINSTANCE hInst = (HINSTANCE)data;

  // Register IPC window class
  WNDCLASSW wc = {};
  wc.lpfnWndProc = IPCWindowProc;
  wc.hInstance = hInst;
  wc.lpszClassName = L"MDropDX12_IPC";
  if (!RegisterClassW(&wc)) {
    if (GetLastError() != ERROR_CLASS_ALREADY_EXISTS)
      return 0;
  }

  // Create hidden window with the configured discoverable title
  HWND hIPC = CreateWindowExW(
    WS_EX_TOOLWINDOW,        // excluded from taskbar and Alt+Tab
    L"MDropDX12_IPC",
    g_szIPCWindowTitle,       // same title as render window (discoverable by Remote)
    WS_POPUP,                 // minimal — no decorations
    0, 0, 0, 0,              // zero size
    NULL, NULL, hInst, NULL);

  if (!hIPC) {
    DebugLogA("IPC thread: CreateWindowExW failed\n");
    return 0;
  }

  // Don't call ShowWindow — keep it hidden but discoverable by EnumWindows
  g_bIPCRunning.store(true);

  wchar_t dbg[512];
  swprintf_s(dbg, L"IPC thread: hidden window created (title: \"%s\", HWND: 0x%p)\n",
             g_szIPCWindowTitle, (void*)hIPC);
  DebugLogW(dbg);

  // Message loop — runs independently of the render thread
  MSG msg;
  while (GetMessage(&msg, NULL, 0, 0) > 0) {
    TranslateMessage(&msg);
    DispatchMessage(&msg);
  }

  DestroyWindow(hIPC);
  UnregisterClassW(L"MDropDX12_IPC", hInst);
  g_bIPCRunning.store(false);

  DebugLogA("IPC thread: exited\n");
  return 0;
}

void StartIPCThread(HINSTANCE hInst) {
  // Copy the render window title for the IPC window
  // (must be set before calling this — uses VisualizerWindowTitle from CreateWindowAndRun)
  threadIPC.store((HANDLE)_beginthreadex(
    nullptr, 0, &IPCWindowThread, (void*)hInst, 0, &threadIPCId));

  if (threadIPC.load())
    DebugLogA("IPC thread: started\n");
  else
    DebugLogA("IPC thread: failed to start\n");
}

void StopIPCThread() {
  HANDLE h = threadIPC.exchange(nullptr);
  if (h) {
    if (threadIPCId != 0)
      PostThreadMessage(threadIPCId, WM_QUIT, 0, 0);
    WaitForSingleObject(h, 3000);
    CloseHandle(h);
    threadIPCId = 0;
    DebugLogA("IPC thread: stopped\n");
  }
}

void InitD3d(HWND hwnd, int width, int height) {
  HRESULT hr;

  // DX12 debug layer disabled — enable manually when diagnosing GPU issues.
  // Uncomment the block below to re-enable (expect 5-10x perf hit):
  // {
  //   ComPtr<ID3D12Debug> debugController;
  //   if (SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debugController)))) {
  //     debugController->EnableDebugLayer();
  //   }
  // }
  UINT dxgiFactoryFlags = 0;

  hr = CreateDXGIFactory2(dxgiFactoryFlags, IID_PPV_ARGS(&pDXGIFactory));
  if (FAILED(hr)) {
    mdropdx12.LogInfo(L"InitD3d: CreateDXGIFactory2 failed");
    return;
  }

  // Choose adapter: prefer the one at g_engine.m_adapterId, fall back to first hardware adapter.
  ComPtr<IDXGIAdapter1> hardwareAdapter;
  UINT wantedIdx = g_engine.m_adapterId;
  for (UINT i = 0; ; i++) {
    ComPtr<IDXGIAdapter1> adapter;
    if (pDXGIFactory->EnumAdapters1(i, &adapter) == DXGI_ERROR_NOT_FOUND)
      break;
    DXGI_ADAPTER_DESC1 desc;
    adapter->GetDesc1(&desc);
    if (desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)
      continue;
    if (SUCCEEDED(D3D12CreateDevice(adapter.Get(), D3D_FEATURE_LEVEL_11_0, _uuidof(ID3D12Device), nullptr))) {
      if (hardwareAdapter == nullptr || i == wantedIdx) {
        hardwareAdapter = adapter;
        if (i == wantedIdx) break;
      }
    }
  }

  hr = D3D12CreateDevice(hardwareAdapter.Get(), D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&pD3DDevice));
  if (FAILED(hr)) {
    mdropdx12.LogInfo(L"InitD3d: D3D12CreateDevice failed");
    return;
  }

  D3D12_COMMAND_QUEUE_DESC queueDesc = {};
  queueDesc.Flags = D3D12_COMMAND_QUEUE_FLAG_NONE;
  queueDesc.Type  = D3D12_COMMAND_LIST_TYPE_DIRECT;
  hr = pD3DDevice->CreateCommandQueue(&queueDesc, IID_PPV_ARGS(&pCommandQueue));
  if (FAILED(hr)) {
    mdropdx12.LogInfo(L"InitD3d: CreateCommandQueue failed");
    return;
  }

  // Set back-buffer dimensions before PluginInitialize creates the swap chain.
  if (!g_engine.IsSpoutActiveAndFixed()) {
    g_engine.SetVariableBackBuffer(width, height);
  }
}

void DeinitD3d() {
  // ComPtrs release automatically; flush any in-flight GPU work first via the
  // plugin's DXContext, which calls WaitForGpu() in its destructor / PluginQuit().
  pCommandQueue.Reset();
  pD3DDevice.Reset();
  pDXGIFactory.Reset();
}

//Multiple monitor stretch - Credit to @milkdropper for the code!
void ToggleStretch(HWND hwnd) {
  if (!stretch) {
    ShowCursor(FALSE);
    int width = GetSystemMetrics(SM_CXVIRTUALSCREEN);
    int height = GetSystemMetrics(SM_CYVIRTUALSCREEN);
    int left = GetSystemMetrics(SM_XVIRTUALSCREEN);
    int top = GetSystemMetrics(SM_YVIRTUALSCREEN);

    if (!fullscreen) {
      lastWindowStyle = GetWindowLongPtr(hwnd, GWL_STYLE);
      lastWindowStyleEx = GetWindowLongPtrW(hwnd, GWL_EXSTYLE);
      lastWindowStyleEx &= ~WS_EX_TOPMOST;
      GetWindowRect(hwnd, &lastRect);
    }

    g_engine.SetVariableBackBuffer(width, height);
    // DX12: swap chain resize is triggered by the WM_SIZE handler after SetWindowPos.
    SetWindowLongPtrW(hwnd, GWL_STYLE, WS_POPUP | WS_VISIBLE);
    SetWindowLongPtrW(hwnd, GWL_EXSTYLE, WS_EX_APPWINDOW);
    SetWindowPos(hwnd, HWND_NOTOPMOST, left, top, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    SetThreadExecutionState(ES_DISPLAY_REQUIRED | ES_CONTINUOUS | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED);
    DragAcceptFiles(hwnd, TRUE);

    stretch = true;
  }
  else {
    ShowCursor(TRUE);

    int x = lastRect.left;
    int y = lastRect.top;
    int width = lastRect.right - lastRect.left;
    int height = lastRect.bottom - lastRect.top;

    g_engine.SetVariableBackBuffer(width, height);
    // DX12: swap chain resize is triggered by the WM_SIZE handler after SetWindowPos.
    SetThreadExecutionState(ES_DISPLAY_REQUIRED | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED);
    stretch = false;

    SetWindowLongPtrW(hwnd, GWL_STYLE, lastWindowStyle);
    SetWindowLongPtrW(hwnd, GWL_EXSTYLE, lastWindowStyleEx);
    SetWindowPos(hwnd, HWND_NOTOPMOST, lastRect.left, lastRect.top, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    SetWindowPos(hwnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE | SWP_NOZORDER);
    if (borderless) {
      SetWindowLongPtrW(hwnd, GWL_STYLE, WS_POPUP | WS_VISIBLE);
      SetWindowPos(hwnd, HWND_TOPMOST, x, y, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    }
  }
  fullscreen = false;
}

static void ToggleClickThrough(HWND hWnd) {
  try {


    // Retrieve the current alpha value
    BYTE currentAlpha = 255; // Default to fully opaque
    DWORD flags = 0;
    COLORREF colorKey = 0;
    if (GetLayeredWindowAttributes(hWnd, &colorKey, &currentAlpha, &flags)) {
      // Successfully retrieved the current alpha value
    }

    if (clickthrough) {
      // Make the window normal while retaining WS_EX_LAYERED
      LONG_PTR style = GetWindowLongPtr(hWnd, GWL_EXSTYLE);
      style &= ~WS_EX_TRANSPARENT; // Remove click-through
      SetWindowLongPtr(hWnd, GWL_EXSTYLE, style);
      SetLayeredWindowAttributes(hWnd, 0, currentAlpha, LWA_ALPHA);
    }
    else {
      // Make the window click-through
      LONG_PTR style = GetWindowLongPtr(hWnd, GWL_EXSTYLE);
      style |= WS_EX_LAYERED | WS_EX_TRANSPARENT;
      SetWindowLongPtr(hWnd, GWL_EXSTYLE, style);
      SetLayeredWindowAttributes(hWnd, 0, currentAlpha, LWA_ALPHA);
    }
    clickthrough = !clickthrough;
  } catch (const std::exception& e) {
    mdropdx12.LogException(L"ToggleClickThrough", e, true);
  }
}

static void ToggleBorderlessFullscreen(HWND hWnd) {
  try {
    static bool previousClickthrough = false; // Store the previous clickthrough state
    static float previousOpacity = 1.0f; // Store the previous opacity (fully opaque by default)

    // Check if Shift is pressed
    bool isShiftPressed = (GetKeyState(VK_SHIFT) & 0x8000) != 0;

    // Get the work area of the monitor (excluding the taskbar)
    MONITORINFO monitorInfo = { sizeof(MONITORINFO) };
    HMONITOR hMonitor = MonitorFromWindow(hWnd, MONITOR_DEFAULTTONEAREST);
    if (GetMonitorInfo(hMonitor, &monitorInfo)) {
      RECT workArea = monitorInfo.rcWork;

      // Check if the window is already in borderless fullscreen mode
      RECT currentRect;
      GetWindowRect(hWnd, &currentRect);

      if (currentRect.left == workArea.left &&
        currentRect.top == workArea.top &&
        currentRect.right == workArea.right &&
        currentRect.bottom == workArea.bottom) {
        // window appears to be borderless fullscreen
        // Restore the previous window dimensions, borderless state, clickthrough state, and opacity
        LONG_PTR style = GetWindowLongPtr(hWnd, GWL_STYLE);
        if (g_engine.m_WindowBorderless) {
          style = WS_POPUP | WS_VISIBLE; // Restore borderless style
        }
        else {
          style = WS_OVERLAPPEDWINDOW | WS_VISIBLE; // Restore normal window style
        }
        SetWindowLongPtr(hWnd, GWL_STYLE, style);

        // Check if the saved dimensions are the same as the current dimensions
        if (g_engine.m_WindowWidth == (currentRect.right - currentRect.left) &&
          g_engine.m_WindowHeight == (currentRect.bottom - currentRect.top)) {
          // Reduce the dimensions by 50%
          g_engine.m_WindowWidth /= 2;
          g_engine.m_WindowHeight /= 2;

          // Center the window
          g_engine.m_WindowX = (workArea.right - workArea.left - g_engine.m_WindowWidth) / 2;
          g_engine.m_WindowY = (workArea.bottom - workArea.top - g_engine.m_WindowHeight) / 2;
        }

        SetWindowPos(
          hWnd,
          g_engine.m_WindowBorderless ? HWND_TOPMOST : HWND_NOTOPMOST,
          g_engine.m_WindowX,
          g_engine.m_WindowY,
          g_engine.m_WindowWidth,
          g_engine.m_WindowHeight,
          SWP_FRAMECHANGED | SWP_NOZORDER | SWP_NOACTIVATE
        );

        // Restore the previous clickthrough state
        if (clickthrough != previousClickthrough) {
          ToggleClickThrough(hWnd);
        }

        if (g_engine.fOpacity != previousOpacity) {
          g_engine.fOpacity = previousOpacity;
          g_engine.SetOpacity(hWnd);
        }

        // Restore the previous opacity
        // SetLayeredWindowAttributes(hWnd, 0, previousOpacity, LWA_ALPHA);

        borderless = g_engine.m_WindowBorderless; // Restore the borderless state
        fullscreen = false;
      }
      else {
        // not in borderless fullscreen mode, so toggle to it
        // Save the current window dimensions, borderless state, clickthrough state, and opacity
        RECT currentWindowRect;
        GetWindowRect(hWnd, &currentWindowRect);
        g_engine.m_WindowX = currentWindowRect.left;
        g_engine.m_WindowY = currentWindowRect.top;
        g_engine.m_WindowWidth = currentWindowRect.right - currentWindowRect.left;
        g_engine.m_WindowHeight = currentWindowRect.bottom - currentWindowRect.top;
        g_engine.m_WindowBorderless = borderless; // Save the current borderless state

        previousClickthrough = clickthrough; // Save the current clickthrough state
        previousOpacity = g_engine.fOpacity;

        // Set the window style to borderless
        LONG_PTR style = GetWindowLongPtr(hWnd, GWL_STYLE);
        style &= ~(WS_OVERLAPPEDWINDOW); // Remove standard window styles
        style |= WS_POPUP; // Add popup style for borderless
        SetWindowLongPtr(hWnd, GWL_STYLE, style);

        // Set the window position and size to fit the work area
        SetWindowPos(
          hWnd,
          isShiftPressed ? HWND_TOPMOST : HWND_NOTOPMOST,
          workArea.left,
          workArea.top,
          workArea.right - workArea.left,
          workArea.bottom - workArea.top,
          SWP_FRAMECHANGED | SWP_NOACTIVATE
        );

        // If Shift is pressed, enable clickthrough
        if (isShiftPressed) {
          if (!clickthrough) {
            ToggleClickThrough(hWnd);
          }
          g_engine.fOpacity = g_engine.m_WindowWatermarkModeOpacity;
          g_engine.SetOpacity(hWnd);
          //SetLayeredWindowAttributes(hWnd, 0, (BYTE)(g_engine.m_WindowWatermarkModeOpacity * 255), LWA_ALPHA);
        }

        g_engine.m_bAlwaysOnTop = isShiftPressed; // Set always on top based on Shift key state
        borderless = true;
      }
    }
  } catch (const std::exception& e) {
    mdropdx12.LogException(L"ToggleBorderlessFullscreen", e, true);
  }
}

static void ToggleFullScreen(HWND hwnd) {
  if (g_engine.IsBorderlessFullscreen(hwnd)) {
    // ShowCursor(TRUE);
    ToggleBorderlessFullscreen(hwnd);
  }
  else if (!fullscreen) {
    ShowCursor(FALSE);

    if (!stretch) {
      lastWindowStyle = GetWindowLongPtr(hwnd, GWL_STYLE);
      lastWindowStyleEx = GetWindowLongPtrW(hwnd, GWL_EXSTYLE);
      lastWindowStyleEx &= ~WS_EX_TOPMOST;
      GetWindowRect(hwnd, &lastRect);
    }

    HMONITOR monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);

    MONITORINFO info;
    info.cbSize = sizeof(MONITORINFO);

    GetMonitorInfoW(monitor, &info);

    int width = info.rcMonitor.right - info.rcMonitor.left;
    int height = info.rcMonitor.bottom - info.rcMonitor.top;

    SetWindowLongPtrW(hwnd, GWL_STYLE, WS_POPUP | WS_VISIBLE);
    SetWindowLongPtrW(hwnd, GWL_EXSTYLE, WS_EX_APPWINDOW);
    SetWindowPos(hwnd, HWND_TOPMOST, info.rcMonitor.left, info.rcMonitor.top, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);

    g_engine.SetVariableBackBuffer(width, height);
    // DX12: swap chain resize is triggered by the WM_SIZE handler after SetWindowPos.

    SetThreadExecutionState(ES_DISPLAY_REQUIRED | ES_CONTINUOUS | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED);
    DragAcceptFiles(hwnd, TRUE);
    fullscreen = true;
  }
  else {
    ShowCursor(TRUE);

    int x = lastRect.left;
    int y = lastRect.top;
    int width = lastRect.right - lastRect.left;
    int height = lastRect.bottom - lastRect.top;

    g_engine.SetVariableBackBuffer(width, height);
    // DX12: swap chain resize is triggered by the WM_SIZE handler after SetWindowPos.
    SetThreadExecutionState(ES_DISPLAY_REQUIRED | ES_SYSTEM_REQUIRED | ES_AWAYMODE_REQUIRED);
    fullscreen = false;

    SetWindowLongPtrW(hwnd, GWL_STYLE, lastWindowStyle);
    SetWindowLongPtrW(hwnd, GWL_EXSTYLE, lastWindowStyleEx);
    SetWindowPos(hwnd, HWND_NOTOPMOST, lastRect.left, lastRect.top, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    SetWindowPos(hwnd, 0, 0, 0, 0, 0, SWP_DRAWFRAME | SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE | SWP_NOZORDER);
    if (borderless) {
      SetWindowLongPtrW(hwnd, GWL_STYLE, WS_POPUP | WS_VISIBLE);
      SetWindowPos(hwnd, HWND_TOPMOST, x, y, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    }
  }
  stretch = false;
}

void SetWindowFixedDimensions(HWND hwnd) {
  int windowX = 0;
  int windowY = 0;

  RECT rect;
  if (GetWindowRect(hwnd, &rect)) {
    windowX = rect.left;
    windowY = rect.top;
  }

  // Restore the window to a normal state if minimized or maximized
  ShowWindow(hwnd, SW_RESTORE);

  // Adjust the window size and position
  SetWindowPos(hwnd, HWND_NOTOPMOST, windowX, windowY, g_engine.m_WindowFixedWidth, g_engine.m_WindowFixedHeight, SWP_FRAMECHANGED | SWP_NOZORDER | SWP_NOACTIVATE);
}

void ResetWindow(HWND hwnd) {
  // Get the screen dimensions
  int screenWidth = GetSystemMetrics(SM_CXSCREEN);
  int screenHeight = GetSystemMetrics(SM_CYSCREEN);

  int windowWidth = screenWidth / 3;
  int windowHeight = screenHeight / 3;

  int windowX = screenWidth - windowWidth - windowWidth / 4;
  int windowY = windowHeight / 4;

  // Restore the window to a normal state if minimized or maximized
  ShowWindow(hwnd, SW_RESTORE);

  // Remove any transparency or click-through flags
  LONG_PTR exStyle = GetWindowLongPtr(hwnd, GWL_EXSTYLE);
  exStyle &= ~(WS_EX_LAYERED | WS_EX_TRANSPARENT); // Remove transparency and click-through
  SetWindowLongPtr(hwnd, GWL_EXSTYLE, exStyle);

  // Reset the window style to a standard overlapped window
  SetWindowLongPtrW(hwnd, GWL_STYLE, WS_OVERLAPPEDWINDOW | WS_VISIBLE);

  // Adjust the window size and position
  SetWindowPos(hwnd, HWND_NOTOPMOST, windowX, windowY, windowWidth, windowHeight, SWP_FRAMECHANGED | SWP_NOZORDER | SWP_NOACTIVATE);

  // Ensure the window is fully opaque
  SetLayeredWindowAttributes(hwnd, 0, 255, LWA_ALPHA);

  g_engine.fOpacity = 1.0f;
  g_engine.m_WindowBorderless = false;
  borderless = false;
  clickthrough = false;
  fullscreen = false;
}

static void ToggleBorderlessWindow(HWND hwnd) {
  static RECT lastRect = { 0 }; // Store the previous window position and size
  GetWindowRect(hwnd, &lastRect);
  int x = lastRect.left;
  int y = lastRect.top;
  int width = lastRect.right - lastRect.left;
  int height = lastRect.bottom - lastRect.top;
  GetWindowRect(hwnd, &lastRect);

  static bool wasTransparent = false; // Track if the window was transparent before toggling

  // Check if the window currently has transparency
  BYTE currentAlpha = 255; // Default to fully opaque
  DWORD flags = 0;
  COLORREF colorKey = 0;
  if (GetLayeredWindowAttributes(hwnd, &colorKey, &currentAlpha, &flags)) {
    wasTransparent = (flags & LWA_COLORKEY) != 0; // Check if LWA_COLORKEY is set
  }

  // --- Preserve current topmost state ---
  // Determine if the window is currently topmost
  HWND hInsertAfter = HWND_NOTOPMOST;
  // WS_EX_TOPMOST is 0x00000008L
  LONG_PTR exStyle = GetWindowLongPtr(hwnd, GWL_EXSTYLE);
  if (exStyle & WS_EX_TOPMOST) {
    hInsertAfter = HWND_TOPMOST;
  }

  if (!borderless) {
    // Save the current window position and size

    // Set the window style to borderless
    SetWindowLongPtrW(hwnd, GWL_STYLE, WS_POPUP | WS_VISIBLE);

    // Reapply transparency only if it was present before
    if (wasTransparent) {
      SetLayeredWindowAttributes(hwnd, RGB(0, 0, 0), 255, LWA_COLORKEY);
    }

    SetWindowPos(hwnd, hInsertAfter, x, y, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    borderless = true;
  }
  else {
    // Restore the previous window style and position
    SetWindowLongPtrW(hwnd, GWL_STYLE, WS_OVERLAPPEDWINDOW | WS_VISIBLE);

    // Reapply transparency only if it was present before
    if (wasTransparent) {
      SetLayeredWindowAttributes(hwnd, RGB(0, 0, 0), 255, LWA_COLORKEY);
    }

    SetWindowPos(hwnd, hInsertAfter, x, y, width, height, SWP_DRAWFRAME | SWP_FRAMECHANGED);
    borderless = false;
  }
  g_engine.m_WindowBorderless = borderless;
}


// -----------------------------------------------------------------------
// Audio Device Selection Dialog
// -----------------------------------------------------------------------

struct AudioDeviceInfo {
  std::wstring friendlyName;
  std::wstring deviceId;
  bool isRender; // true = speaker/headphone (loopback), false = microphone
};

static std::vector<AudioDeviceInfo> g_dialogDevices;
static int g_dialogSelectedIndex = -1;

static HRESULT EnumerateAudioDevices(std::vector<AudioDeviceInfo>& devices) {
  devices.clear();
  HRESULT hr = S_OK;

  IMMDeviceEnumerator* pEnum = nullptr;
  hr = CoCreateInstance(__uuidof(MMDeviceEnumerator), NULL, CLSCTX_ALL,
                        __uuidof(IMMDeviceEnumerator), (void**)&pEnum);
  if (FAILED(hr)) return hr;
  ReleaseOnExit releaseEnum(pEnum);

  // Enumerate render devices (speakers/headphones — for loopback capture)
  for (int pass = 0; pass < 2; pass++) {
    bool isRender = (pass == 0);
    IMMDeviceCollection* pCollection = nullptr;
    hr = pEnum->EnumAudioEndpoints(isRender ? eRender : eCapture,
                                    DEVICE_STATE_ACTIVE, &pCollection);
    if (FAILED(hr)) continue;
    ReleaseOnExit releaseCollection(pCollection);

    UINT count = 0;
    pCollection->GetCount(&count);

    for (UINT i = 0; i < count; i++) {
      IMMDevice* pDevice = nullptr;
      hr = pCollection->Item(i, &pDevice);
      if (FAILED(hr)) continue;
      ReleaseOnExit releaseDevice(pDevice);

      // Get device ID
      LPWSTR pwszId = nullptr;
      pDevice->GetId(&pwszId);
      std::wstring deviceId = pwszId ? pwszId : L"";
      if (pwszId) CoTaskMemFree(pwszId);

      // Get friendly name
      IPropertyStore* pProps = nullptr;
      hr = pDevice->OpenPropertyStore(STGM_READ, &pProps);
      if (FAILED(hr)) continue;
      ReleaseOnExit releaseProps(pProps);

      PROPVARIANT pv;
      PropVariantInit(&pv);
      hr = pProps->GetValue(PKEY_Device_FriendlyName, &pv);
      if (FAILED(hr)) continue;
      PropVariantClearOnExit clearPv(&pv);

      if (pv.vt == VT_LPWSTR) {
        AudioDeviceInfo info;
        info.friendlyName = pv.pwszVal;
        info.deviceId = deviceId;
        info.isRender = isRender;
        devices.push_back(info);
      }
    }
  }

  return S_OK;
}

// Dialog control IDs
#define IDC_DEVICE_LIST   1001
#define IDC_OK_BTN        IDOK
#define IDC_CANCEL_BTN    IDCANCEL

static INT_PTR CALLBACK AudioDeviceDlgProc(HWND hDlg, UINT msg, WPARAM wParam, LPARAM lParam) {
  switch (msg) {
    case WM_INITDIALOG: {
      HWND hList = GetDlgItem(hDlg, IDC_DEVICE_LIST);

      // Find current device name for highlighting
      std::wstring currentDevice = g_engine.m_szAudioDevice;
      int currentType = g_engine.m_nAudioDeviceRequestType;
      int selectIndex = -1;

      for (size_t i = 0; i < g_dialogDevices.size(); i++) {
        const auto& dev = g_dialogDevices[i];
        std::wstring label = dev.friendlyName;
        if (dev.isRender)
          label += L"  [Loopback]";
        else
          label += L"  [Microphone]";

        int idx = (int)SendMessageW(hList, LB_ADDSTRING, 0, (LPARAM)label.c_str());
        SendMessageW(hList, LB_SETITEMDATA, idx, (LPARAM)i);

        // Match current device
        if (_wcsicmp(dev.friendlyName.c_str(), currentDevice.c_str()) == 0) {
          bool typeMatch = (currentType == 0) ||
                           (currentType == 2 && dev.isRender) ||
                           (currentType == 1 && !dev.isRender);
          if (typeMatch) selectIndex = idx;
        }
      }

      if (selectIndex >= 0)
        SendMessageW(hList, LB_SETCURSEL, selectIndex, 0);
      else if (g_dialogDevices.size() > 0)
        SendMessageW(hList, LB_SETCURSEL, 0, 0);

      // Center dialog on parent
      RECT rcParent, rcDlg;
      GetWindowRect(GetParent(hDlg), &rcParent);
      GetWindowRect(hDlg, &rcDlg);
      int x = rcParent.left + ((rcParent.right - rcParent.left) - (rcDlg.right - rcDlg.left)) / 2;
      int y = rcParent.top + ((rcParent.bottom - rcParent.top) - (rcDlg.bottom - rcDlg.top)) / 2;
      SetWindowPos(hDlg, NULL, x, y, 0, 0, SWP_NOSIZE | SWP_NOZORDER);

      return TRUE;
    }

    case WM_COMMAND:
      switch (LOWORD(wParam)) {
        case IDOK: {
          HWND hList = GetDlgItem(hDlg, IDC_DEVICE_LIST);
          int sel = (int)SendMessageW(hList, LB_GETCURSEL, 0, 0);
          if (sel != LB_ERR) {
            g_dialogSelectedIndex = (int)SendMessageW(hList, LB_GETITEMDATA, sel, 0);
          }
          EndDialog(hDlg, IDOK);
          return TRUE;
        }
        case IDCANCEL:
          EndDialog(hDlg, IDCANCEL);
          return TRUE;

        case IDC_DEVICE_LIST:
          if (HIWORD(wParam) == LBN_DBLCLK) {
            // Double-click acts like OK
            SendMessageW(hDlg, WM_COMMAND, IDOK, 0);
            return TRUE;
          }
          break;
      }
      break;

    case WM_CLOSE:
      EndDialog(hDlg, IDCANCEL);
      return TRUE;
  }
  return FALSE;
}

// Build an in-memory DLGTEMPLATE — no .rc file needed
static void ShowAudioDeviceDialog(HWND hParent) {
  // Enumerate devices first
  EnumerateAudioDevices(g_dialogDevices);
  g_dialogSelectedIndex = -1;

  if (g_dialogDevices.empty()) {
    MessageBoxW(hParent, L"No audio devices found.", L"MDropDX12 Audio", MB_OK | MB_ICONWARNING);
    return;
  }

  // Build in-memory dialog template
  // Layout: Title bar, listbox, OK and Cancel buttons
  // Dialog: 340x260 DLUs
  const int DLG_W = 340;
  const int DLG_H = 260;
  const int LIST_X = 10, LIST_Y = 10, LIST_W = 320, LIST_H = 210;
  const int BTN_W = 60, BTN_H = 18;
  const int OK_X = DLG_W - BTN_W * 2 - 20, OK_Y = DLG_H - BTN_H - 10;
  const int CANCEL_X = DLG_W - BTN_W - 10, CANCEL_Y = OK_Y;

  // Allocate buffer for dialog template + 3 controls
  // Each item needs DLGITEMTEMPLATE + class + text + extra, all WORD-aligned
  BYTE buf[2048];
  memset(buf, 0, sizeof(buf));
  BYTE* p = buf;

  // --- DLGTEMPLATE ---
  DLGTEMPLATE* pDlg = (DLGTEMPLATE*)p;
  pDlg->style = DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU | DS_SETFONT;
  pDlg->cdit = 3; // listbox + OK + Cancel
  pDlg->cx = DLG_W;
  pDlg->cy = DLG_H;
  pDlg->x = 0;
  pDlg->y = 0;
  p += sizeof(DLGTEMPLATE);

  // Menu (none)
  *(WORD*)p = 0; p += sizeof(WORD);
  // Class (default)
  *(WORD*)p = 0; p += sizeof(WORD);
  // Title
  const wchar_t* title = L"Select Audio Device";
  size_t titleLen = (wcslen(title) + 1) * sizeof(WCHAR);
  memcpy(p, title, titleLen);
  p += titleLen;
  // Font size (DS_SETFONT)
  *(WORD*)p = 10; p += sizeof(WORD);
  // Font name
  const wchar_t* fontName = L"Segoe UI";
  size_t fontLen = (wcslen(fontName) + 1) * sizeof(WCHAR);
  memcpy(p, fontName, fontLen);
  p += fontLen;

  // --- Helper lambda for DWORD alignment ---
  auto align4 = [&]() {
    while ((ULONG_PTR)p % sizeof(DWORD))
      *p++ = 0;
  };

  // --- Listbox control ---
  align4();
  DLGITEMTEMPLATE* pItem = (DLGITEMTEMPLATE*)p;
  pItem->style = WS_CHILD | WS_VISIBLE | WS_BORDER | WS_VSCROLL | WS_TABSTOP | LBS_NOTIFY | LBS_NOINTEGRALHEIGHT;
  pItem->dwExtendedStyle = 0;
  pItem->x = LIST_X;
  pItem->y = LIST_Y;
  pItem->cx = LIST_W;
  pItem->cy = LIST_H;
  pItem->id = IDC_DEVICE_LIST;
  p += sizeof(DLGITEMTEMPLATE);
  // Class: Listbox = 0x0083
  *(WORD*)p = 0xFFFF; p += sizeof(WORD);
  *(WORD*)p = 0x0083; p += sizeof(WORD);
  // Text (empty)
  *(WORD*)p = 0; p += sizeof(WORD);
  // Extra data
  *(WORD*)p = 0; p += sizeof(WORD);

  // --- OK button ---
  align4();
  pItem = (DLGITEMTEMPLATE*)p;
  pItem->style = WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON;
  pItem->dwExtendedStyle = 0;
  pItem->x = OK_X;
  pItem->y = OK_Y;
  pItem->cx = BTN_W;
  pItem->cy = BTN_H;
  pItem->id = IDOK;
  p += sizeof(DLGITEMTEMPLATE);
  // Class: Button = 0x0080
  *(WORD*)p = 0xFFFF; p += sizeof(WORD);
  *(WORD*)p = 0x0080; p += sizeof(WORD);
  // Text: "OK"
  const wchar_t* okText = L"OK";
  size_t okLen = (wcslen(okText) + 1) * sizeof(WCHAR);
  memcpy(p, okText, okLen);
  p += okLen;
  // Extra data
  *(WORD*)p = 0; p += sizeof(WORD);

  // --- Cancel button ---
  align4();
  pItem = (DLGITEMTEMPLATE*)p;
  pItem->style = WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON;
  pItem->dwExtendedStyle = 0;
  pItem->x = CANCEL_X;
  pItem->y = CANCEL_Y;
  pItem->cx = BTN_W;
  pItem->cy = BTN_H;
  pItem->id = IDCANCEL;
  p += sizeof(DLGITEMTEMPLATE);
  // Class: Button = 0x0080
  *(WORD*)p = 0xFFFF; p += sizeof(WORD);
  *(WORD*)p = 0x0080; p += sizeof(WORD);
  // Text: "Cancel"
  const wchar_t* cancelText = L"Cancel";
  size_t cancelLen = (wcslen(cancelText) + 1) * sizeof(WCHAR);
  memcpy(p, cancelText, cancelLen);
  p += cancelLen;
  // Extra data
  *(WORD*)p = 0; p += sizeof(WORD);

  INT_PTR result = DialogBoxIndirectParamW(
    GetModuleHandle(NULL),
    (DLGTEMPLATE*)buf,
    hParent,
    AudioDeviceDlgProc,
    0
  );

  if (result == IDOK && g_dialogSelectedIndex >= 0 && g_dialogSelectedIndex < (int)g_dialogDevices.size()) {
    const auto& selected = g_dialogDevices[g_dialogSelectedIndex];

    // Save previous device
    wcscpy_s(g_engine.m_szAudioDevicePrevious, g_engine.m_szAudioDevice);
    g_engine.m_nAudioDevicePreviousType = g_engine.m_nAudioDeviceActiveType;

    // Set new device
    wcscpy_s(g_engine.m_szAudioDevice, selected.friendlyName.c_str());
    g_engine.m_nAudioDeviceRequestType = selected.isRender ? 2 : 1;
    g_engine.SetAudioDeviceDisplayName(selected.friendlyName.c_str(), selected.isRender);

    // Save to settings.ini
    g_engine.MyWriteConfig();

    // Trigger audio thread restart
    g_engine.m_nAudioLoopState = 1;

    wchar_t logBuf[512];
    swprintf_s(logBuf, L"Audio device selected: %s [%s]",
               selected.friendlyName.c_str(),
               selected.isRender ? L"Loopback" : L"Microphone");
    DebugLogW(logBuf);
  }
}

HRESULT GetDefaultAudioDeviceName(IMMDevice** ppMMDevice, std::wstring* m_szAudioDeviceDisplayName) {
  HRESULT hr = S_OK;
  IMMDeviceEnumerator* pMMDeviceEnumerator;

  // activate a device enumerator
  hr = CoCreateInstance(
    __uuidof(MMDeviceEnumerator), NULL, CLSCTX_ALL,
    __uuidof(IMMDeviceEnumerator),
    (void**)&pMMDeviceEnumerator
  );
  if (FAILED(hr)) {
    ERR(L"CoCreateInstance(IMMDeviceEnumerator) failed: hr = 0x%08x", hr);
    return hr;
  }
  ReleaseOnExit releaseMMDeviceEnumerator(pMMDeviceEnumerator);

  // get the default render endpoint
  hr = pMMDeviceEnumerator->GetDefaultAudioEndpoint(eRender, eConsole, ppMMDevice);
  if (FAILED(hr)) {
    ERR(L"IMMDeviceEnumerator::GetDefaultAudioEndpoint failed: hr = 0x%08x", hr);
    return hr;
  }

  // open the property store on that device
  IPropertyStore* pPropertyStore;
  hr = (*ppMMDevice)->OpenPropertyStore(STGM_READ, &pPropertyStore);
  if (FAILED(hr)) {
    ERR(L"IMMDevice::OpenPropertyStore failed: hr = 0x%08x", hr);
    return hr;
  }
  ReleaseOnExit releasePropertyStore(pPropertyStore);

  // get the long name property
  PROPVARIANT pv; PropVariantInit(&pv);
  hr = pPropertyStore->GetValue(PKEY_Device_FriendlyName, &pv);
  if (FAILED(hr)) {
    ERR(L"IPropertyStore::GetValue failed: hr = 0x%08x", hr);
    return hr;
  }
  PropVariantClearOnExit clearPv(&pv);

  if (VT_LPWSTR != pv.vt) {
    ERR(L"PKEY_Device_FriendlyName variant type is %u - expected VT_LPWSTR", pv.vt);
    return E_UNEXPECTED;
  }
  *m_szAudioDeviceDisplayName = std::wstring(pv.pwszVal);

  return S_OK;
}

LRESULT CALLBACK StaticWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) {

  static bool rightMouseButtonHeld = false; // Track the state of the right mouse button  

  switch (uMsg) {
  case WM_CLOSE:
  {
    g_engine.SaveWindowSizeAndPosition(hWnd);
    DestroyWindow(hWnd);
    UnregisterClassW(L"Direct3DWindowClass", NULL);
    return 0;
  }

  case WM_DESTROY:
  {
    PostQuitMessage(0);
    break;
  }

  case WM_MOVE:
  {
    // Get the current window rectangle
    RECT windowRect;
    GetWindowRect(hWnd, &windowRect);

    // Get the virtual screen area (spanning all monitors)
    int virtualLeft = GetSystemMetrics(SM_XVIRTUALSCREEN);
    int virtualTop = GetSystemMetrics(SM_YVIRTUALSCREEN);
    int virtualWidth = GetSystemMetrics(SM_CXVIRTUALSCREEN);
    int virtualHeight = GetSystemMetrics(SM_CYVIRTUALSCREEN);

    int virtualRight = virtualLeft + virtualWidth;
    int virtualBottom = virtualTop + virtualHeight;

    int windowWidth = windowRect.right - windowRect.left;
    int windowHeight = windowRect.bottom - windowRect.top;

    // Constrain the window to stay within the virtual screen area
    int newX = windowRect.left;
    int newY = windowRect.top;

    if (newX < virtualLeft) {
      newX = virtualLeft;
    }
    if (newY < virtualTop) {
      newY = virtualTop;
    }
    if (newX + windowWidth > virtualRight) {
      newX = virtualRight - windowWidth;
    }
    if (newY + windowHeight > virtualBottom) {
      newY = virtualBottom - windowHeight;
    }

    // Set the new position if adjustments were made
    if (newX != windowRect.left || newY != windowRect.top) {
      SetWindowPos(hWnd, NULL, newX, newY, 0, 0, SWP_NOSIZE | SWP_NOZORDER | SWP_NOACTIVATE);
    }
    break;
  }

  case WM_KEYDOWN:
  {
    g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
  }
  if (wParam == VK_F2) {
    bool isCtrlPressed = (GetKeyState(VK_CONTROL) & 0x8000) != 0;
    if (isCtrlPressed) {
      bool isShiftPressed = (GetKeyState(VK_SHIFT) & 0x8000) != 0;
      if (isShiftPressed) {
        SetWindowFixedDimensions(hWnd);
      }
      else {
        ResetWindow(hWnd);
      }
    }
    else if (!fullscreen && !stretch) {
      ToggleBorderlessWindow(hWnd);
    }
  }
  if (wParam == VK_F9) {
    bool isCtrlPressed = (GetKeyState(VK_CONTROL) & 0x8000) != 0;
    if (isCtrlPressed) {
      ToggleBorderlessFullscreen(hWnd);
    }
    else {
      ToggleClickThrough(hWnd);
      if (clickthrough) {
        g_engine.AddNotification(L"Clickthrough Mode enabled");
      }
      else {
        g_engine.AddNotification(L"Clickthrough Mode disabled");
      }
    }
  }
  else if (wParam == VK_C) {
    if (GetKeyState(VK_CONTROL) & 0x8000) { // Check if Ctrl is pressed
      g_engine.m_DisplayCover = !g_engine.m_DisplayCover;
      mdropdx12.doSaveCover = g_engine.m_DisplayCover;
      if (g_engine.m_DisplayCover) {
        g_engine.AddNotification(L"Cover Display enabled");
      }
      else {
        g_engine.AddNotification(L"Cover Display disabled");
      }
    }
    return 0;
  }
  else if (wParam == VK_D) {
    if (GetKeyState(VK_CONTROL) & 0x8000) { // Check if Ctrl is pressed
      bool isShiftPressed = (GetKeyState(VK_SHIFT) & 0x8000) != 0;
      if (isShiftPressed) {
        g_engine.AddNotification(g_engine.m_szAudioDeviceDisplayName);
      }
      else {
        wcscpy_s(g_engine.m_szAudioDevicePrevious, g_engine.m_szAudioDevice);
        g_engine.m_nAudioDevicePreviousType = g_engine.m_nAudioDeviceActiveType;

        IMMDevice* m_pMMDevice;
        std::wstring sAudioDeviceDisplayName;
        GetDefaultAudioDeviceName(&m_pMMDevice, &sAudioDeviceDisplayName);
        wcscpy(g_engine.m_szAudioDevice, sAudioDeviceDisplayName.c_str());

        g_engine.SetAudioDeviceDisplayName(sAudioDeviceDisplayName.c_str(), true);

        // Restart audio
        g_engine.m_nAudioDeviceRequestType = 2;
        g_engine.m_nAudioLoopState = 1;
      }
    }
    return 0;
  }
  else if (wParam == VK_A) {
    if (GetKeyState(VK_CONTROL) & 0x8000) { // Ctrl+A = audio device dialog
      ShowAudioDeviceDialog(hWnd);
      return 0;
    }
  }
  else if (wParam == VK_M) {
    if (GetKeyState(VK_CONTROL) & 0x8000) { // Check if Ctrl is pressed
      g_engine.m_bEnableMouseInteraction = !g_engine.m_bEnableMouseInteraction;
      if (g_engine.m_bEnableMouseInteraction) {
        g_engine.AddNotification(L"Mouse interaction enabled");
      }
      else {
        g_engine.AddNotification(L"Mouse interaction disabled");
      }
    }
  }

  case WM_NCHITTEST: //used for borderless window
  {
    // if (borderless)
    if (!fullscreen && !stretch) {
      // resizable borderless
      // from https://stackoverflow.com/questions/19106047/winapi-c-reprogramming-window-resize
#define BORDERWIDTH  10
#define TITLEBARWIDTH  30
      RECT rect;
      int x, y;
      GetWindowRect(hWnd, &rect);

      x = GET_X_LPARAM(lParam) - rect.left;
      y = GET_Y_LPARAM(lParam) - rect.top;

      // When mouse interaction is enabled, let the plugin handle client-area mouse events.
      // Still allow resizing by returning the correct HT* edge codes for the border zones.
      if (g_engine.m_bEnableMouseInteraction && !(GetAsyncKeyState(VK_LBUTTON) & 0x8000)) {
        if (x < BORDERWIDTH && y < BORDERWIDTH)
          return HTTOPLEFT;
        else if (x > rect.right - rect.left - BORDERWIDTH && y < BORDERWIDTH)
          return HTTOPRIGHT;
        else if (x > rect.right - rect.left - BORDERWIDTH && y > rect.bottom - rect.top - BORDERWIDTH)
          return HTBOTTOMRIGHT;
        else if (x < BORDERWIDTH && y > rect.bottom - rect.top - BORDERWIDTH)
          return HTBOTTOMLEFT;
        else if (x < BORDERWIDTH)
          return HTLEFT;
        else if (y < BORDERWIDTH)
          return HTTOP;
        else if (x > rect.right - rect.left - BORDERWIDTH)
          return HTRIGHT;
        else if (y > rect.bottom - rect.top - BORDERWIDTH)
          return HTBOTTOM;

        // interior -> client area (so MyWindowProc receives mouse messages)
        return HTCLIENT;
      }

      // Default (existing) behavior when mouse interaction is disabled:
      if (x >= BORDERWIDTH && x <= rect.right - rect.left - BORDERWIDTH && y >= BORDERWIDTH && y <= TITLEBARWIDTH)
        return HTCAPTION;

      else if (x < BORDERWIDTH && y < BORDERWIDTH)
        return HTTOPLEFT;
      else if (x > rect.right - rect.left - BORDERWIDTH && y < BORDERWIDTH)
        return HTTOPRIGHT;
      else if (x > rect.right - rect.left - BORDERWIDTH && y > rect.bottom - rect.top - BORDERWIDTH)
        return HTBOTTOMRIGHT;
      else if (x < BORDERWIDTH && y > rect.bottom - rect.top - BORDERWIDTH)
        return HTBOTTOMLEFT;

      else if (x < BORDERWIDTH)
        return HTLEFT;
      else if (y < BORDERWIDTH)
        return HTTOP;
      else if (x > rect.right - rect.left - BORDERWIDTH)
        return HTRIGHT;
      else if (y > rect.bottom - rect.top - BORDERWIDTH)
        return HTBOTTOM;
      return HTCAPTION;
    }
    break;
  }

  case WM_NCLBUTTONDBLCLK:
  {
    if (fullscreen) {
      ToggleFullScreen(hWnd);
      return 0;
    }

    bool ctrlHeld = (GetKeyState(VK_CONTROL) & 0x8000) != 0;
    if (ctrlHeld) {
      ToggleBorderlessWindow(hWnd);
      return 0;
    }

    ToggleFullScreen(hWnd);
    return 0;
  }

  case WM_NCRBUTTONDBLCLK:
  {
    ToggleBorderlessWindow(hWnd);
    break;
  }

  case WM_SYSKEYDOWN:
  {
    if (wParam == VK_F4) { // SPOUT ??
      PostQuitMessage(0);
    }
    else if (wParam == 'S' || wParam == 's') {
      ToggleStretch(hWnd);
    }
    else if (wParam == VK_RETURN) {
      ToggleFullScreen(hWnd);
    }
    else {
      g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }
    break;
  }

  case WM_RBUTTONDOWN:
  case WM_NCRBUTTONDOWN: // Right mouse button pressed
    // If plugin-level mouse interaction is enabled, let the plugin handle the event.
    rightMouseButtonHeld = true;
    if (g_engine.m_bEnableMouseInteraction) {
      return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }
    break;

  case WM_RBUTTONUP:
  case WM_NCRBUTTONUP: // Right mouse button released
    rightMouseButtonHeld = false;
    if (g_engine.m_bEnableMouseInteraction) {
      return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }
    break;

  case WM_LBUTTONDOWN:
  case WM_NCLBUTTONDOWN: // Left mouse button pressed
    if (rightMouseButtonHeld) {
      // Right + Left
      PostMessage(hWnd, WM_CLOSE, 0, 0); // Close the window
    }
    else {
      return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }
    break;

  case WM_LBUTTONUP:
  case WM_NCLBUTTONUP: // Left mouse button released
    //if (g_engine.m_bEnableMouseInteraction) {
    return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    //}
    // no special action on left button up in existing logic
    break;

  case WM_MBUTTONDOWN:
  case WM_NCMBUTTONDOWN: // Middle mouse button clicked
    if (rightMouseButtonHeld) {
      // Right + Middle
      g_engine.OpenMDropDX12Remote();
    }
    break;

  case WM_LBUTTONDBLCLK:
  {
    // If we're currently fullscreen, always exit fullscreen on a left-button double-click
    // anywhere in the client area (there is no title bar in fullscreen).
    if (fullscreen) {
      ToggleFullScreen(hWnd);
      return 0;
    }

    bool ctrlHeld = (GetKeyState(VK_CONTROL) & 0x8000) != 0;
    if (ctrlHeld) {
      ToggleBorderlessWindow(hWnd);
      return 0;
    }

    // Determine position relative to window
    RECT rect; GetWindowRect(hWnd, &rect);
    int y = GET_Y_LPARAM(lParam) - rect.top;
    bool inTitle = (y <= TITLEBARWIDTH);

    // If plugin mouse interaction is enabled and the dblclick is in client area,
    // let the plugin handle it. Otherwise toggle fullscreen.
    if (g_engine.m_bEnableMouseInteraction && !inTitle) {
      return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }

    ToggleFullScreen(hWnd);
    return 0;
  }

  case WM_RBUTTONDBLCLK:
  {
    if (g_engine.m_bEnableMouseInteraction) {
      return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
    }
    ToggleBorderlessWindow(hWnd);
    break;
  }

  default:
    return g_engine.PluginShellWindowProc(hWnd, uMsg, wParam, lParam);
  }

  return DefWindowProc(hWnd, uMsg, wParam, lParam);
}


// Full device teardown and recreation — used for TDR recovery and user-triggered restart.
static void PerformDeviceRecovery() {
  g_engine.m_bDeviceRecoveryPending = false;

  HWND hwnd = g_engine.GetPluginWindow();
  if (!hwnd) return;

  RECT rc;
  GetClientRect(hwnd, &rc);
  int w = rc.right - rc.left;
  int h = rc.bottom - rc.top;
  if (w <= 0 || h <= 0) { w = 960; h = 540; }

  mdropdx12.LogInfo(L"Device Recovery: Attempting full device recreation");
  DebugLogA("Device Recovery: Beginning teardown and recreation");

  // 1. Full plugin teardown (releases all GPU resources + DXContext)
  g_engine.PluginQuit();

  // 2. Release D3D12 device and command queue
  DeinitD3d();

  // 3. Brief pause to let the GPU/driver finish resetting
  Sleep(500);

  // 4. Recreate D3D12 device and command queue
  InitD3d(hwnd, w, h);
  if (!pD3DDevice || !pCommandQueue) {
    mdropdx12.LogInfo(L"Device Recovery: InitD3d FAILED — cannot recover");
    DebugLogA("Device Recovery: InitD3d FAILED");
    return;
  }

  // 5. Reinitialize the plugin with the fresh device
  int ok = g_engine.PluginInitialize(
    pD3DDevice.Get(), pCommandQueue.Get(), pDXGIFactory.Get(),
    hwnd, w, h);

  if (!ok) {
    mdropdx12.LogInfo(L"Device Recovery: PluginInitialize FAILED — cannot recover");
    DebugLogA("Device Recovery: PluginInitialize FAILED");
    return;
  }

  // 6. Force dimension sync (same as initial startup)
  if (g_engine.m_lpDX && g_engine.m_lpDX->m_ready) {
    GetClientRect(hwnd, &rc);
    int actualW = rc.right - rc.left;
    int actualH = rc.bottom - rc.top;
    if (actualW > 0 && actualH > 0 &&
        (actualW != g_engine.m_lpDX->m_client_width ||
         actualH != g_engine.m_lpDX->m_client_height)) {
      g_engine.OnUserResizeWindow();
    }
  }

  // 7. Skip to next preset (the current one likely caused the crash)
  g_engine.NextPreset(0.0f);

  mdropdx12.LogInfo(L"Device Recovery: Device recreated successfully — skipped to next preset");
  DebugLogA("Device Recovery: SUCCESS — device recreated, advanced to next preset");

  wchar_t msg[256];
  swprintf(msg, 256, L"Device recovered — skipped to next preset");
  g_engine.AddError(msg, 8.0f, ERR_NOTIFY, true);
}

void RenderFrame() {

  // Check for user-triggered device restart BEFORE rendering
  // (avoids submitting commands to a doomed/crashed device)
  if (g_engine.m_bDeviceRecoveryPending) {
    PerformDeviceRecovery();
    return;
  }

  {
    std::unique_lock<std::mutex> lock(pcmMutex);
    memcpy(pcmLeftOut, pcmLeftIn, SAMPLE_SIZE);
    memcpy(pcmRightOut, pcmRightIn, SAMPLE_SIZE);
    memset(pcmLeftIn, 128, SAMPLE_SIZE);   // 128 = silence in unsigned 8-bit PCM
    memset(pcmRightIn, 128, SAMPLE_SIZE);
  }

  mdropdx12.PollMediaInfo();
  if (mdropdx12.coverUpdated) {
    g_engine.PostMessageToMDropDX12Remote(WM_USER_COVER_CHANGED);
    mdropdx12.coverUpdated = false;
  }
  if (mdropdx12.updated) {
    bool wasExplicit = mdropdx12.doPollExplicit;

    if (mdropdx12.isSongChange && !wasExplicit) {
      if (g_engine.m_ChangePresetWithSong) {
        g_engine.NextPreset(g_engine.m_fBlendTimeAuto);
      }
      if (g_engine.m_DisplayCover) {
        g_engine.LaunchSprite(0, -1);
      }
    }

    if (wasExplicit && g_engine.m_DisplayCoverWhenPressingB) {
      g_engine.LaunchSprite(0, -1);
    }

    mdropdx12.doPollExplicit = false;

    // Only display song info on actual track change or explicit user request
    // (skip initial detection on startup to avoid showing stale media titles)
    if (mdropdx12.isSongChange || wasExplicit) {
      wchar_t buf[512];

      // Convert wchar_t array to std::string
      std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
      std::string format = converter.to_bytes(g_engine.m_SongInfoFormat);
      std::istringstream stream(format);
      std::vector<std::string> tokens;
      std::string token;

      // Split the string into tokens
      while (std::getline(stream, token, ';')) {
        tokens.push_back(token);
      }

      // remove existing song info display
      g_engine.ClearErrors(ERR_MSG_BOTTOM_EXTRA_1);
      g_engine.ClearErrors(ERR_MSG_BOTTOM_EXTRA_2);
      g_engine.ClearErrors(ERR_MSG_BOTTOM_EXTRA_3);

      // Iterate over tokens in reverse order
      for (auto it = tokens.rbegin(); it != tokens.rend(); ++it) {
        std::string currentToken = *it;

        // Convert token to lowercase for case-insensitive comparison
        std::transform(currentToken.begin(), currentToken.end(), currentToken.begin(), ::tolower);

        if (currentToken == "artist") {
          if (mdropdx12.currentArtist.length() > 0) {
            wcscpy(buf, mdropdx12.currentArtist.c_str());
            g_engine.AddError(buf, g_engine.m_SongInfoDisplaySeconds, ERR_MSG_BOTTOM_EXTRA_1, false);
          }
        }
        else if (currentToken == "title") {
          if (mdropdx12.currentTitle.length() > 0) {
            wcscpy(buf, mdropdx12.currentTitle.c_str());
            g_engine.AddError(buf, g_engine.m_SongInfoDisplaySeconds, ERR_MSG_BOTTOM_EXTRA_2, false);
          }
        }
        else if (currentToken == "album") {
          if (mdropdx12.currentAlbum.length() > 0) {
            wcscpy(buf, mdropdx12.currentAlbum.c_str());
            g_engine.AddError(buf, g_engine.m_SongInfoDisplaySeconds, ERR_MSG_BOTTOM_EXTRA_3, false);
          }
        }
      }
    }

    mdropdx12.updated = false;
  }

  g_engine.PluginRender(
    (unsigned char*)pcmLeftOut,
    (unsigned char*)pcmRightOut);

  // --- TDR Recovery: detect device-lost and attempt full device recreation ---
  if (g_engine.m_bDeviceRecoveryPending) {
    PerformDeviceRecovery();
  }
}

unsigned __stdcall CreateWindowAndRun(void* data) {

  HINSTANCE instance = (HINSTANCE)data;

#ifdef DEBUG
  _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
  _CrtSetBreakAlloc(60);
#endif

  // SPOUT
  // Set Per Monitor awareness
  SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE); //older Windows versions: Entry Point Not Found Fix
  // SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE);

  // Register the windows class
  WNDCLASSW wndClass;
  wndClass.style = CS_DBLCLKS;
  wndClass.lpfnWndProc = StaticWndProc;
  wndClass.cbClsExtra = 0;
  wndClass.cbWndExtra = 0;
  wndClass.hInstance = instance;
  wndClass.hIcon = LoadIconW(instance, MAKEINTRESOURCEW(IDI_ENGINE_ICON));
  wndClass.hCursor = LoadCursor(NULL, IDC_ARROW);
  wndClass.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
  wndClass.lpszMenuName = NULL;
  wndClass.lpszClassName = L"Direct3DWindowClass";

  if (!RegisterClassW(&wndClass)) {
    DWORD dwError = GetLastError();
    if (dwError != ERROR_CLASS_ALREADY_EXISTS) {
      return 0;
    }
  }

  // SPOUT
  // Make the window a fixed size
    // The sender resolution is independent - see SpoutWidth/SpoutHeight below
  int windowWidth = 1280; // standalone version 1280x720
  int windowHeight = 720;

  RECT rc;
  SetRect(&rc, 0, 0, windowWidth, windowHeight);
  AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, false);

  // SPOUT
  // Centre on the desktop work area
  int WindowPosLeft = 0;
  int WindowPosTop = 0;
  RECT WorkArea;
  SystemParametersInfo(SPI_GETWORKAREA, 0, (LPVOID)&WorkArea, 0);
  WindowPosLeft += ((WorkArea.right - WorkArea.left) - windowWidth) / 2;
  WindowPosTop += ((WorkArea.bottom - WorkArea.top) - windowHeight) / 2;

  // SPOUT
  // Remove minimize and maximize
  //DWORD dwStyle = (WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME);

  // ===============================================
  // Enumerate other instances of BeatDrop to increment the title
  WCHAR VisualizerWindowTitle[256];
  // printf("Number of existing BeatDrops (%d)\n", nBeatDrops);

  // Use configured title or default
  const wchar_t* baseTitle = (g_engine.m_szWindowTitle[0] != L'\0')
    ? g_engine.m_szWindowTitle
    : L"MDropDX12 Visualizer";

  bool freeTitleFound = false;
  nBeatDrops = 0;

  while (!freeTitleFound && nBeatDrops < 100) {
    if (nBeatDrops == 0) {
      lstrcpyW(VisualizerWindowTitle, baseTitle);
    }
    else {
      swprintf_s(VisualizerWindowTitle, L"%s %d", baseTitle, nBeatDrops + 1);
    }

    // Check if a window with this title already exists
    HWND existing = FindWindowW(L"Direct3DWindowClass", VisualizerWindowTitle);
    if (existing != NULL) {
      nBeatDrops++;
      // Try next title
    }
    else {
      // No window with this title, so we can use it
      printf("New title [%S]\n", VisualizerWindowTitle);
      freeTitleFound = true;
    }
  }

  mdropdx12.LogInfo(L"CreateWindowAndRun: Creating window");

  if (g_engine.m_WindowX == 0 || g_engine.m_WindowY == 0 || g_engine.m_WindowWidth == 0 || g_engine.m_WindowHeight == 0) {
    RECT workArea{};
    if (!SystemParametersInfoW(SPI_GETWORKAREA, 0, &workArea, 0)) {
      workArea.left = 0;
      workArea.top = 0;
      workArea.right = GetSystemMetrics(SM_CXSCREEN);
      workArea.bottom = GetSystemMetrics(SM_CYSCREEN);
    }

    const int gapPx = 50;
    int spanWidth = workArea.right - workArea.left;
    int spanHeight = workArea.bottom - workArea.top;
    int defaultWidth = spanWidth > 0 ? spanWidth / 3 : 640;
    int defaultHeight = spanHeight > 0 ? spanHeight / 3 : 360;
    if (defaultWidth <= 0) {
      defaultWidth = 640;
    }
    if (defaultHeight <= 0) {
      defaultHeight = 360;
    }

    g_engine.m_WindowWidth = defaultWidth;
    g_engine.m_WindowHeight = defaultHeight;
    g_engine.m_WindowX = (workArea.right - gapPx) - g_engine.m_WindowWidth;
    g_engine.m_WindowY = workArea.top + gapPx;
  }


  // Create the render window
  HWND hwnd = CreateWindowW(
    L"Direct3DWindowClass",
    VisualizerWindowTitle,
    WS_OVERLAPPEDWINDOW, // SPOUT
    //dwStyle,
    g_engine.m_WindowX,
    g_engine.m_WindowY,
    g_engine.m_WindowWidth,
    g_engine.m_WindowHeight,
    0,
    NULL,
    instance,
    0);

  if (!hwnd) {
    mdropdx12.LogInfo(L"CreateWindowAndRun: No window handle!");
    DWORD dwError = GetLastError();
    return 0;
  }

  // Publish render window HWND for the IPC thread
  g_hRenderWindow.store(hwnd);

  // Start IPC hidden window thread (non-blocking WM_COPYDATA handler)
  lstrcpyW(g_szIPCWindowTitle, VisualizerWindowTitle);
  StartIPCThread(instance);

  if (!icon) {
    icon = LoadIconW(instance, MAKEINTRESOURCEW(IDI_ENGINE_ICON));
  }

  SendMessageW(hwnd, WM_SETICON, ICON_BIG, (LPARAM)icon);
  SendMessageW(hwnd, WM_SETICON, ICON_SMALL, (LPARAM)icon);

  // window was closed in borderless fullscreen mode
  if (g_engine.IsBorderlessFullscreen(hwnd)) {
    g_engine.fOpacity = g_engine.m_WindowWatermarkModeOpacity;
    g_engine.SetOpacity(hwnd);
    if (!clickthrough) ToggleClickThrough(hwnd);
    g_engine.m_bAlwaysOnTop = true;
    g_engine.ToggleAlwaysOnTop(hwnd);
  }
  else {
    if (g_engine.fOpacity < 1) {
      g_engine.SetOpacity(hwnd);
    }
  }

  if (IsWindow(hwnd)) {
    ShowWindow(hwnd, SW_SHOW);
  }
  else {
    mdropdx12.LogInfo(L"CreateWindowAndRun: ShowWindow failed, window not created");
  }

  if (g_engine.m_bAlwaysOnTop) {
    g_engine.ToggleAlwaysOnTop(hwnd);
  }
  if (g_engine.m_WindowBorderless && !borderless) {
    ToggleBorderlessWindow(hwnd);
  }

  // always ensure .Init is called after the window is created (ShowWindow above)
  mdropdx12.Init(g_engine.m_szBaseDir);
  mdropdx12.doPoll = g_engine.m_SongInfoPollingEnabled;
  mdropdx12.doSaveCover = g_engine.m_DisplayCover;

  unsigned int frame = 0;


  // MDropDX12: Moved to StartThreads()
  // g_engine.PluginPreInitialize(0, 0);

  // SPOUT

  // Use actual client area dimensions (not window dimensions which include title bar + borders)
  RECT clientRect;
  GetClientRect(hwnd, &clientRect);
  unsigned int BackbufferWidth = clientRect.right - clientRect.left;
  unsigned int BackbufferHeight = clientRect.bottom - clientRect.top;
  if (BackbufferWidth == 0 || BackbufferHeight == 0) {
    // Fallback to window dimensions if client rect is not yet available
    BackbufferWidth = g_engine.m_WindowWidth;
    BackbufferHeight = g_engine.m_WindowHeight;
  }
  if (g_engine.IsSpoutActiveAndFixed()) {
    BackbufferWidth = g_engine.nSpoutFixedWidth;
    BackbufferHeight = g_engine.nSpoutFixedHeight;
  }

  mdropdx12.LogInfo(L"CreateWindowAndRun: InitD3d");
  InitD3d(hwnd, BackbufferWidth, BackbufferHeight);

  mdropdx12.LogInfo(L"CreateWindowAndRun: PluginInitialize");
  g_engine.PluginInitialize(
    pD3DDevice.Get(),
    pCommandQueue.Get(),
    pDXGIFactory.Get(),
    hwnd,
    BackbufferWidth,
    BackbufferHeight);

  // Force dimension correction: WM_SIZE from ShowWindow was missed because m_lpDX
  // was null at that time. Verify dimensions match the actual client rect now.
  if (g_engine.m_lpDX && g_engine.m_lpDX->m_ready) {
    RECT rc;
    GetClientRect(hwnd, &rc);
    int actualW = rc.right - rc.left;
    int actualH = rc.bottom - rc.top;
    if (actualW > 0 && actualH > 0 &&
        (actualW != g_engine.m_lpDX->m_client_width ||
         actualH != g_engine.m_lpDX->m_client_height)) {
      wchar_t dbg[256];
      swprintf(dbg, 256, L"DX12 init correction: swap chain %dx%d -> client %dx%d\n",
               g_engine.m_lpDX->m_client_width, g_engine.m_lpDX->m_client_height,
               actualW, actualH);
      DebugLogW(dbg);
      g_engine.OnUserResizeWindow();
    }
  }

  MSG msg;
  msg.message = WM_NULL;

  try {
    mdropdx12.LogInfo(L"CreateWindowAndRun: Message loop starting");

    PeekMessage(&msg, NULL, 0U, 0U, PM_NOREMOVE);
    while (WM_QUIT != msg.message) {
      try {
        if (PeekMessage(&msg, NULL, 0U, 0U, PM_REMOVE) != 0) {
          TranslateMessage(&msg);
          DispatchMessage(&msg);
        }
        else if (!pauseRender) {
          GetAudioBuf(pcmLeftIn, pcmRightIn, SAMPLE_SIZE);
          RenderFrame();
        }
      } catch (const std::exception& e) {
        try {
          // Convert exception message (UTF-8) to wide string for logging
          std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
          std::wstring emsg = converter.from_bytes(e.what());
          std::wstring logMsg = L"Exception in render loop: " + emsg;
          mdropdx12.LogInfo(logMsg);
        } catch (...) {
          mdropdx12.LogInfo(L"Exception in render loop (failed to convert exception message)");
        }
      } catch (...) {
        mdropdx12.LogInfo(L"Unknown non-standard exception in render loop");
      }
      frame++;
    }
  } catch (const std::exception& e) {
    mdropdx12.LogException(L"CreateWindowAndRun: Exception in main loop", e, true);
  }
  mdropdx12.LogInfo(L"CreateWindowAndRun: Message loop ended");

  // Stop IPC thread before tearing down the render window
  StopIPCThread();
  g_hRenderWindow.store(nullptr);

  g_engine.MyWriteConfig();
  g_engine.PluginQuit();

  DeinitD3d();

  threadRender = nullptr;
  threadId = 0;

  return 0;
}

void StartRenderThread(HINSTANCE instance) {
  threadRender = (HANDLE)_beginthreadex(
    nullptr,
    0,
    &CreateWindowAndRun,
    (void*)instance,
    0,
    &threadId);
}

static int StartAudioCaptureThread(HINSTANCE instance, int nestingLevel) {

  try {

    HRESULT hr = S_OK;

    hr = CoInitialize(NULL);
    if (FAILED(hr)) {
      ERR(L"CoInitialize failed: hr = 0x%08x", hr);
      return -__LINE__;
    }
    CoUninitializeOnExit cuoe;

    // argc==1 No additional params. Output disabled.
    // argc==3 Two additional params. Output file enabled (32bit IEEE 754 FLOAT).
    // argc==4 Three additional params. Output file enabled (LITTLE ENDIAN PCM).
    int argc = 1;
    // LPCWSTR argv[4] = { L"", L"--file", L"loopback-capture.wav", L"--int-16" };
    LPCWSTR argv[4] = { L"", L"", L"", L"" };

    if (wcslen(g_engine.m_szAudioDevice) > 0) {
      argc = 3;
      argv[1] = L"--device";
      argv[2] = g_engine.m_szAudioDevice;
    };

    /*
    L"%ls [--device \"Device long name\"] [--file \"file name\"] [--int-16]\n"
      L"\n"
      L"    -? prints this message.\n"
      L"    --list-devices displays the long names of all active playback devices.\n"
      L"    --device captures from the specified device (default if omitted)\n"
      L"    --file saves the output to a file (%ls if omitted)\n"
      L"    --int-16 attempts to coerce data to 16-bit integer format",
     */

    hr = S_OK;

    CPrefs prefs(argc, argv, hr, g_engine.m_nAudioDeviceRequestType);
    if (FAILED(hr)) {
      ERR(L"CPrefs::CPrefs constructor failed: hr = 0x%08x", hr);
      return -__LINE__;
    }
    if (S_FALSE == hr) {
      // nothing to do
      return 0;
    }

    // create a "loopback capture has started" event
    HANDLE hStartedEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    if (NULL == hStartedEvent) {
      ERR(L"CreateEvent failed: last error is %u", GetLastError());
      return -__LINE__;
    }
    CloseHandleOnExit closeStartedEvent(hStartedEvent);

    // create a "stop capturing now" event
    HANDLE hStopEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    if (NULL == hStopEvent) {
      ERR(L"CreateEvent failed: last error is %u", GetLastError());
      return -__LINE__;
    }
    CloseHandleOnExit closeStopEvent(hStopEvent);

  g_engine.SetAudioDeviceDisplayName(prefs.m_szAudioDeviceDisplayName.c_str(), prefs.m_bIsRenderDevice);

    {
      const wchar_t* requestTypeText = L"auto";
      if (g_engine.m_nAudioDeviceRequestType == 1) {
        requestTypeText = L"capture";
      }
      else if (g_engine.m_nAudioDeviceRequestType == 2) {
        requestTypeText = L"render";
      }

      wchar_t configBuf[512];
      swprintf_s(
        configBuf,
        L"StartAudioCaptureThread: device='%ls' requestType=%ls isRender=%ls int16=%ls",
        prefs.m_szAudioDeviceDisplayName.c_str(),
        requestTypeText,
        prefs.m_bIsRenderDevice ? L"true" : L"false",
        prefs.m_bInt16 ? L"true" : L"false"
      );
      mdropdx12.LogDebug(configBuf);
    }

    // create arguments for loopback capture thread
    LoopbackCaptureThreadFunctionArguments threadArgs;
    threadArgs.hr = E_UNEXPECTED; // thread will overwrite this
    threadArgs.pMMDevice = prefs.m_pMMDevice;
    threadArgs.bIsRenderDevice = prefs.m_bIsRenderDevice;
    threadArgs.bInt16 = prefs.m_bInt16;
    threadArgs.hFile = prefs.m_hFile;
    threadArgs.hStartedEvent = hStartedEvent;
    threadArgs.hStopEvent = hStopEvent;
    threadArgs.nFrames = 0;
    threadArgs.pMDropDX12 = &mdropdx12; // provide MDropDX12 instance for logging from the capture thread

    mdropdx12.LogInfo(L"StartAudioCaptureThread: CreateThread LoopbackCaptureThreadFunction");
    hThreadLoopbackCapture = CreateThread(
      NULL, 0,
      LoopbackCaptureThreadFunction, &threadArgs,
      0, NULL
    );
    if (NULL == hThreadLoopbackCapture) {
      mdropdx12.LogInfo(L"StartAudioCaptureThread: CreateThread failed");
      ERR(L"CreateThread failed: last error is %u", GetLastError());
      return -__LINE__;
    }
    CloseHandleOnExit closeThread(hThreadLoopbackCapture);

    // wait for either capture to start or the thread to end
    HANDLE waitArray[2] = { hStartedEvent, hThreadLoopbackCapture };
    DWORD dwWaitResult;
    dwWaitResult = WaitForMultipleObjects(
      ARRAYSIZE(waitArray), waitArray,
      FALSE, INFINITE
    );

    if (WAIT_OBJECT_0 + 1 == dwWaitResult) {
      mdropdx12.LogInfo(L"StartAudioCaptureThread: Thread aborted before starting to loopback capture: hr = 0x%08x");
      ERR(L"Thread aborted before starting to loopback capture: hr = 0x%08x", threadArgs.hr);
      return -__LINE__;
    }

    if (WAIT_OBJECT_0 != dwWaitResult) {
      mdropdx12.LogInfo(L"StartAudioCaptureThread: Unexpected WaitForMultipleObjects return value");
      ERR(L"Unexpected WaitForMultipleObjects return value %u", dwWaitResult);
      return -__LINE__;
    }

    // at this point capture is running
    // wait for the user to press a key or for capture to error out

    // /*HANDLE thread =*/ 
    // StartRenderThread(instance);
    // WaitForSingleObject(threadRender, INFINITE);

    //NEED TO STOP CAPTURE
    // at this point capture is running
    // wait for the user to press a key or for capture to error out
    {
      WaitForSingleObjectOnExit waitForThread(hThreadLoopbackCapture);
      SetEventOnExit setStopEvent(hStopEvent);

      /*
      HANDLE hStdIn = GetStdHandle(STD_INPUT_HANDLE);

      if (INVALID_HANDLE_VALUE == hStdIn) {
          ERR(L"GetStdHandle returned INVALID_HANDLE_VALUE: last error is %u", GetLastError());
          return -__LINE__;
      }

      LOG(L"%s", L"Press Enter to quit...");

      HANDLE rhHandles[2] = { hThreadLoopbackCapture, hStdIn };
      */
      g_engine.m_nAudioLoopState = 0;
      bool bKeepWaiting = true;
      while (bKeepWaiting) {
        if (threadRender == nullptr) {
          // render thread stopped
          bKeepWaiting = false;
        }
        else if (g_engine.m_nAudioLoopState == 1) {
          // audio device changed
          bKeepWaiting = false;
          g_engine.m_nAudioLoopState = 2;
        }
        else {
          Sleep(100);
        }
      } // while
    } // naked scope

    // at this point the thread is definitely finished

  // MessageBoxA(NULL, "capture loop finished", "loopback", MB_OK);

    DWORD exitCode;
    if (!GetExitCodeThread(hThreadLoopbackCapture, &exitCode)) {
      mdropdx12.LogInfo(L"StartAudioCaptureThread: GetExitCodeThread failed");
      ERR(L"GetExitCodeThread failed: last error is %u", GetLastError());
      return -__LINE__;
    }

    if (0 != exitCode) {
      mdropdx12.LogInfo(L"StartAudioCaptureThread: Loopback capture thread exit code unexpected");
      ERR(L"Loopback capture thread exit code is %u; expected 0", exitCode);
      return -__LINE__;
    }

    if (S_OK != threadArgs.hr) {
      ERR(L"Thread HRESULT is 0x%08x", threadArgs.hr);
      // return -__LINE__;
      // probably the device got disconnected, see handling for result > 0 below
      // if this is the topmost thread, do not return
      if (nestingLevel > 0) {
        return 1;
      }
    }
    // let prefs' destructor call mmioClose

    if (g_engine.m_nAudioLoopState == 2) {
      g_engine.AddNotificationAudioDevice();

      // not the best solution to build a thread tree like this, but too lazy/scared to refactor right now
      int result = StartAudioCaptureThread(instance, ++nestingLevel);
      if (result != 0) {
        ERR(L"StartAudioCaptureThread failed: %d", result);

        /*
        std::wstringstream ss;
        ss << L"STATUS=Device init \"" << g_engine.m_szAudioDeviceDisplayName << "\" failed, reverting to \"" << g_engine.m_szAudioDevicePrevious << "\"";
        statusMessage = ss.str();
        g_engine.SendMessageToMDropDX12Remote(statusMessage.data());
        */

        // if result > 1, we probably encountered a disconnection error earlier (eg. Bluetooth headphone disconnection), 
        // and the m_szAudioDevice was already set using Ctrl+D
        if (result < 0) {
          wcscpy_s(g_engine.m_szAudioDevice, g_engine.m_szAudioDevicePrevious);
          bool prevIsRender = (g_engine.m_nAudioDevicePreviousType == 2);
          g_engine.SetAudioDeviceDisplayName(g_engine.m_szAudioDevicePrevious, prevIsRender);
          g_engine.m_nAudioDeviceActiveType = g_engine.m_nAudioDevicePreviousType;
        }

        std::wstring statusMessage = L"DEVICE=" + std::wstring(g_engine.m_szAudioDevice);
        g_engine.SendMessageToMDropDX12Remote(statusMessage.data());
        g_engine.AddNotificationAudioDevice();
        result = StartAudioCaptureThread(instance, ++nestingLevel);
      }
    }
  } catch (const std::exception& e) {
    mdropdx12.LogException(L"StartAudioCaptureThread", e, true);
  }
  return 0;
}

unsigned __stdcall DoSetup(void* param) {

  Sleep(3000); // wait for the render thread to initialize the plugin completely
  HINSTANCE instance = (HINSTANCE)param;

  if (g_engine.m_ShaderCaching && g_engine.m_ShaderPrecompileOnStartup) {

    std::wstring cacheDir = std::wstring(g_engine.m_szBaseDir) + L"cache";
    std::wstring compiledListPath = cacheDir + L"\\compiled.txt";

    // Abort if compiled.txt already exists
    if (std::filesystem::exists(compiledListPath)) {
      mdropdx12.LogInfo(L"Shader cache already exists, skipping precompilation");
      return -1;
    }

    // Open precompile.txt
    std::ifstream file("precompile.txt");
    if (!file.is_open()) {
      mdropdx12.LogInfo(L"Failed to open precompile.txt");
      return -1;
    }

    // Ensure the "cache" directory exists
    try {
      std::filesystem::create_directory(cacheDir);
    } catch (const std::filesystem::filesystem_error& e) {
      mdropdx12.LogException(L"Failed to create cache directory", e, false);
      return -1;
    }

    // Prepare output file for compiled shader list
    std::wofstream compiledList(compiledListPath);
    if (!compiledList.is_open()) {
      std::wstring msg = L"Precompile failed to create " + compiledListPath;
      wchar_t* writableMsg = &msg[0];  // Get non-const pointer to internal buffer
      g_engine.AddNotification(writableMsg);
      return -1;
    }

    // Set UTF-8 locale for the output stream
    compiledList.imbue(std::locale(std::locale::empty(), new std::codecvt_utf8<wchar_t>));

    g_engine.AddNotification(L"Shader cache empty, precompiling shaders", 10 * 60);

    int compiledShaders = 0;
    std::string line;
    auto start = std::chrono::high_resolution_clock::now();
    while (std::getline(file, line)) {
      // Skip BOM if present (UTF-8)
      if (!line.empty() && line[0] == '\xEF' && line[1] == '\xBB' && line[2] == '\xBF') {
        line.erase(0, 3);
      }

      // Convert UTF-8 to wide string properly
      std::wstring wLine;
      if (!line.empty()) {
        int size_needed = MultiByteToWideChar(CP_UTF8, 0, &line[0], (int)line.size(), NULL, 0);
        wLine.resize(size_needed);
        MultiByteToWideChar(CP_UTF8, 0, &line[0], (int)line.size(), &wLine[0], size_needed);
      }

      // Trim whitespace
      wLine.erase(0, wLine.find_first_not_of(L" \t"));
      wLine.erase(wLine.find_last_not_of(L" \t") + 1);

      // Skip empty lines or comments
      if (wLine.empty() || wLine[0] == L'#') continue;

      // Check for wildcard
      if (!wLine.empty() && wLine.back() == L'*') {
        std::wstring dirPath = wLine.substr(0, line.length() - 1); // Remove '*'
        if (std::filesystem::exists(dirPath)) {
          for (const auto& entry : std::filesystem::directory_iterator(dirPath)) {
            if (entry.is_regular_file()) {
              PrecompilePresetShaders(entry.path().wstring(), compiledList, compiledShaders);
            }
          }
        }
      }
      else {
        PrecompilePresetShaders(wLine, compiledList, compiledShaders);
      }
    }

    file.close();
    compiledList.close();
    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration<double>(end - start); // fractional seconds
    std::wstringstream ss;
    ss << std::fixed << std::setprecision(2) << duration.count();

    std::wstring message = L"Precompiling " + std::to_wstring(compiledShaders)
      + L" shaders completed in " + ss.str() + L"s";

    wchar_t szMessage[256];
    wcsncpy_s(szMessage, message.c_str(), _TRUNCATE);
    g_engine.AddNotification(szMessage, 5);
    mdropdx12.LogInfo(message);
  }
  return 0;
}

void PrecompilePresetShaders(std::wstring& wLine, std::wofstream& compiledList, int& compiledShaders) {
  wchar_t szFile[512];
  // Treat anything without a drive letter as relative
  if (wLine.find(L":\\") == std::wstring::npos) {
    lstrcpyW(szFile, g_engine.m_szBaseDir);
    lstrcatW(szFile, wLine.c_str());
  }
  else {
    lstrcpyW(szFile, wLine.c_str());
  }

  // Compile the shader
  if (std::filesystem::exists(std::filesystem::path(szFile))) {
    auto start = std::chrono::high_resolution_clock::now();
    g_engine.CompilePresetShadersToFile(szFile);
    auto end = std::chrono::high_resolution_clock::now();
    auto durationMs = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
    std::wstring warn = L" ";
    if (durationMs > 1000) {
      // if compilation took more than 1 second, add a warning
      warn = L"!";

    }
    compiledList << warn << std::setw(8) << std::setfill(L' ') << durationMs << " " << szFile << std::endl;
    compiledShaders++;
  }
}

void StartSetupThread(HINSTANCE instance) {
  threadSetup = (HANDLE)_beginthreadex(
    nullptr,
    0,
    &DoSetup,
    (void*)instance,
    0,
    &threadId);
}

int StartThreads(HINSTANCE instance) {
  try {
    // MDropDX12: early init so we can read from settings
    g_engine.PluginPreInitialize(0, 0);

    // early assignment so we can use logging
    // mdropdx12.Init() may only be called after the window is created due to threading issues
    mdropdx12.logLevel = g_engine.m_LogLevel;
    g_engine.mdropdx12 = &mdropdx12;

    mdropdx12.LogInfo(L"MDropDX12 initialized, LogLevel=" + std::to_wstring(mdropdx12.logLevel)
      + L" BaseDir=" + g_engine.m_szBaseDir);

    // DX12: no legacy DirectX 9 DLL checks needed.

    mdropdx12.LogInfo(L"Starting render thread");
    StartRenderThread(instance);
    // WaitForSingleObject(threadRender, INFINITE);

    mdropdx12.LogInfo(L"Starting setup thread");
    StartSetupThread(instance);

    if (g_engine.m_bEnableAudioCapture) {
      mdropdx12.LogInfo(L"Starting audio capture thread");
      StartAudioCaptureThread(instance, 0);
    }
    else {
      mdropdx12.LogInfo(L"Audio capture disabled in settings");
      while (true) {
        Sleep(1000);
      }
    }

  } catch (const std::exception& e) {
    mdropdx12.LogException(L"StartThreads", e, true);
    return -1;
  }

  return 0;
}

void MDropDX12TerminateHandler() {
  try {
    // Re-throw the current exception to get its type/info
    std::exception_ptr exptr = std::current_exception();
    if (exptr) {
      try {
        std::rethrow_exception(exptr);
      } catch (const std::exception& e) {
        mdropdx12.LogException(L"Unhandled exception (std::terminate)", e, true);
      } catch (...) {
        mdropdx12.LogInfo(L"Unhandled non-std::exception in std::terminate");
      }
    }
    else {
      mdropdx12.LogInfo(L"std::terminate called with no active exception");
    }
  } catch (...) {
    // If logging itself throws, do nothing
  }
  std::abort(); // Ensure abnormal termination
}

void SeTranslatorFunction(unsigned int code, _EXCEPTION_POINTERS* ep) {
  try {
    std::ostringstream oss;
    oss << "SEH exception code0x" << std::hex << code;
    throw std::runtime_error(oss.str());
  } catch (...) {
    // If translator itself fails, rethrow as runtime_error
    throw std::runtime_error("SEH exception (unknown)");
  }
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR szCmdLine, int iCmdShow) {
  std::set_terminate(MDropDX12TerminateHandler);
  api_orig_hinstance = hInstance;

  // Install SEH -> C++ translator so SEH (e.g., access violations) become catchable std::exception
  _set_se_translator(SeTranslatorFunction);

  // Determine m_szBaseDir: the directory that contains the "resources" folder.
  // Walk upward from the exe location (handles Debug/, Release/, and install layouts).
  {
    wchar_t exePath[MAX_PATH];
    GetModuleFileNameW(NULL, exePath, MAX_PATH);

    fs::path dir = fs::path(exePath).parent_path();

    // Walk up at most 4 levels looking for resources\data\include.fx
    bool found = false;
    for (int i = 0; i < 5; i++) {
      if (fs::exists(dir / L"resources" / L"data" / L"include.fx")) {
        found = true;
        break;
      }
      fs::path parent = dir.parent_path();
      if (parent == dir) break;  // filesystem root
      dir = parent;
    }

    std::wstring baseDir = dir.wstring();
    if (!baseDir.empty() && baseDir.back() != L'\\') {
      baseDir += L'\\';
    }
    wcscpy_s(g_engine.m_szBaseDir, MAX_PATH, baseDir.c_str());

    // Initialize debug log (rotates debug.log → debug.prev.log)
    DebugLogInit(g_engine.m_szBaseDir);

    DebugLogW(found ? L"BaseDir resolved (resources found)" : L"BaseDir resolved (resources NOT found)");
    DebugLogW(g_engine.m_szBaseDir);
  }
  int res = 0;
  try {
    res = StartThreads(hInstance);
  } catch (const std::exception& e) {
    mdropdx12.LogException(L"WinMain", e, true);
  }
  mdropdx12.LogInfo(L"WinMain ended, result=" + std::to_wstring(res));
  return res;
}

static std::string title;

#ifdef DEBUG
struct _DEBUG_STATE {
  _DEBUG_STATE() {}

  ~_DEBUG_STATE() {
    _CrtDumpMemoryLeaks();
  }
};

_DEBUG_STATE ds;
#endif